import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from 'next/legacy/image'
import orlundo from "../public/new_orlundo.png";
import snappy from "../public/snappy.png";
import merkle from "../public/merkleme.png";
import r21 from "../public/r21.png";
import aliens from "../public/aliens.png";
import Link from "next/link";


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Orlundo Hubbard</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <Link
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/files/orlundo_engineering.pdf" target="_blank"
                >
                  Resume
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Orlundo Hubbard
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software engineer and Animator.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I'm a software engineer based out of Austin, Texas with experience in building production ready projects. I've worked with technologies such as JavaScript (React, NextJs), SQL, and Python. I also have a strong background in working with team collaboration tools such as Figma, Jira and Github. 
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Link href="https://twitter.com/OrlundoH" target="_blank" >
               
              <AiFillTwitterCircle />
             
              </Link>
              <Link href="https://www.linkedin.com/in/orlundo-hubbard-2175b9154/" target="_blank">
              
              <AiFillLinkedin />
              
              </Link>
              <Link href="https://www.youtube.com/channel/UCHYaK3nQSsNyGP70JRnqHPw" target="_blank">
               
              <AiFillYoutube />
              
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={orlundo} layout="fill" objectFit="scale-down" className="" alt="orlundo" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
             <Image src={code} width={100} height={100} alt="code" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Code
              </h3>
              <p className="py-2">
                I've had experience in a professional setting with the following languages:
              </p>
              <h4 className="py-4 text-teal-600">Languages I've used</h4>
              <p className="text-gray-800 py-1">JavaScript (React, NextJs)</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">MySQL</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image src={design} width={100} height={100} alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Design
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="consulting" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-5xl  text-center py-1 dark:text-white ">Portofolio projects</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Link href="https://snappypiranhas.io/" target="_blank">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout = "responsive"
                src={snappy}
                alt="snappy"
              />
             
              </Link>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Link href="https://www.merkleme.io/" target="_blank">
              <Image
                className="rounded-lg object-fit"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={merkle}
                alt="merkle"
              />
             </Link>
            </div>
            
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Link href="https://www.round21.com/pages/nfts" target="_blank">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={r21}
                alt="r21"
              />
              
              </Link>
            </div>
            
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Link href="https://fugly.app/" target="_blank">
             
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={aliens}
                alt="aliens"
              />
              
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
